CREATE TABLE AREA_ALMACENAMIENTO(
ID_ALMACENAMIENTO VARCHAR(255),
CONSTRAINT PK_AREA_ALMACENAMIENTO PRIMARY KEY (ID_ALMACENAMIENTO)
);

CREATE TABLE EQUIPOS(
ID_EQUIPO VARCHAR(255),
CANTIDAD FLOAT,
CAPACIDAD FLOAT(255),
CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_EQUIPO),
CONSTRAINT CK_CANTIDAD CHECK (CANTIDAD>=0),
CONSTRAINT CK_CAPACIDAD CHECK (CAPACIDAD>=0)
);

CREATE TABLE BODEGAS(
ID_BODEGA VARCHAR(255),
ANCHO FLOAT,
LARGO FLOAT,
PLATAFORMA BOOLEAN,
SEPARACION_COLUMNA FLOAT,
CONSTRAINT PK_BODEGA PRIMARY KEY (ID_BODEGA),
CONSTRAINT CK_ANCHO CHECK (ANCHO>=0),
CONSTRAINT CK_LARGO CHECK (LARGO>=0),
CONSTRAINT NN_PLATAFORMA CHECK(PLATAFORMA IS NOT NULL),
CONSTRAINT CK_SEPARACION_COLUMNA CHECK (SEPARACION_COLUMNA>=0)
);


CREATE TABLE SILO(
ID_SILO VARCHAR(255),
NOMBRE VARCHAR(255),
CAPACIDAD FLOAT,
CONSTRAINT PK_SILO PRIMARY KEY(ID_SILO),
CONSTRAINT NN_NOMBRE CHECK(NOMBRE IS NOT NULL),
CONSTRAINT CK_CAPACIDAD CHECK (CAPACIDAD >=0)
);

CREATE TABLE COBERTIZO(
ID_COBERTIZO VARCHAR(255),
DIMEN FLOAT,
TIPO_CARGA VARCHAR(255),
CONSTRAINT PK_COBERTIZO PRIMARY KEY (ID_COBERTIZO),
CONSTRAINT CK_DIMEN CHECK (DIMEN>=0),
CONSTRAINT NN_TIPO_CARGA CHECK(TIPO_CARGA IS NOT NULL)
);

CREATE TABLE PATIOS(
ID_PATIO VARCHAR(255),
DIMEN FLOAT,
TIPO_CARGA VARCHAR(255),
CONSTRAINT PK_PATIO PRIMARY KEY (ID_PATIO),
CONSTRAINT CK_DIMEN CHECK (DIMEN>=0),
CONSTRAINT NN_TIPO_CARGA CHECK (TIPO_CARGA IS NOT NULL)
);

CREATE TABLE CUARTO_FRIO(
ID_CUARTO VARCHAR(255),
ID_BODEGA VARCHAR(255),
AREA FLOAT,
LARGO FLOAT,
AREA_BODEGA FLOAT,
CONSTRAINT PK_CUARTO PRIMARY KEY (ID_CUARTO),
CONSTRAINT FK_BODEGA FOREIGN KEY (ID_BODEGA)
              REFERENCES BODEGAS (ID_BODEGA),
CONSTRAINT CK_AREA CHECK (AREA>=0),
CONSTRAINT CK_LARGO CHECK (LARGO>=0),
CONSTRAINT CK_AREA_BODEGA CHECK (AREA_BODEGA>=0)
);

CREATE TABLE BUQUES(
ID_BUQUE VARCHAR(255),
NOMBRE VARCHAR(255),
NOMBRE_AGENTE VARCHAR(255),
REGISTRO_CAPITANIA VARCHAR(255),
CONSTRAINT PK_BUQUE PRIMARY KEY (ID_BUQUE),
CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_NOMBRE_AGENTE CHECK (NOMBRE_AGENTE IS NOT NULL),
CONSTRAINT NN_REGISTRO_CAPITANIA CHECK (REGISTRO_CAPITANIA IS NOT NULL)
);

CREATE TABLE BUQUE_PORTACOTENEDOR(
ID_BUQUE VARCHAR(255),
CAPACIDAD FLOAT,
CONSTRAINT FK_ID_BUQUE FOREIGN KEY (ID_BUQUE)
     REFERENCES BUQUES (ID_BUQUE),
CONSTRAINT CK_CAPACIDAD CHECK (CAPACIDAD>=0)
);

CREATE TABLE BUQUE_RORO(
ID_BUQUE VARCHAR(255),
CONSTRAINT FK_ID_BUQUE FOREIGN KEY (ID_BUQUE)
     REFERENCES BUQUES (ID_BUQUE)
);

CREATE TABLE BUQUE_MULTIPROPOSITO(
ID_BUQUE VARCHAR(255),
CONSTRAINT FK_ID_BUQUE FOREIGN KEY (ID_BUQUE)
     REFERENCES BUQUES (ID_BUQUE)
);

CREATE TABLE CAMION(
ID_CAMION VARCHAR(255),
CONSTRAINT PK_ID_CAMION PRIMARY KEY (ID_CAMION)
);

CREATE TABLE LLEGADA_BUQUE(
FECHA DATE,
HORA TIME,
ID_BUQUE VARCHAR(255),
CONSTRAINT PK_BUQUE PRIMARY KEY (ID_BUQUE),
CONSTRAINT FK_BUQUE FOREIGN KEY (ID_BUQUE)
      REFERENCES BUQUES (ID_BUQUE),
CONSTRAINT PK_FECHA PRIMARY KEY (FECHA),
CONSTRAINT PK_HORA PRIMARY KEY (HORA)
);

CREATE TABLE IMPORTADOR(
ID_IMPORTADOR VARCHAR(255),
NOMBRE VARCHAR(255),
REGISTRO_ADUANA LONG ,
TIPO VARCHAR(255),
CONSTRAINT PK_IMPORTADOR PRIMARY KEY (ID_IMPORTADOR),
CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL),
CONSTRAINT CK_REGISTRO CHECK (REGISTRO_ADUANA >=0),
CONSTRAINT NN_TIPO CHECK (TIPO IS NOT NULL)
);

CREATE TABLE EXPORTADOR (
ID_EXPORTADOR VARCHAR(255),
NOMBRE VARCHAR(255),
RUT lONG,
CONSTRAINT PK_EXPORTADOR PRIMARY KEY (ID_EXPORTADOR),
CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL),
CONSTRAINT PK_RUT PRIMARY KEY (RUT)
);

CREATE TABLE FACTURAS(
ID_FACTURA VARCHAR(255),
FECHA DATE,
ID_EXPORTADOR VARCHAR(255),
ID_BUQUE VARCHAR(255),
CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA),
CONSTRAINT NN_FEHCHA CHECK(FECHA IS NOT NULL),
CONSTRAINT FK_EXPORTADOR FOREIGN KEY (ID_EXPORTADOR)
        REFERENCES EXPORTADOR (ID_EXPORTADOR),
CONSTRAINT FK_BUQUE FOREIGN KEY (ID_BUQUE),
     REFERENCES BUQUES (ID_BUQUE)
);

CREATE TABLE CARGAS_ASOCIADAS_FACTURAS(
ID_FACTURA VARCHAR(255),
ID_MERCANCIA VARCHAR(255),
CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT FK_FACTURA FOREIGN KEY (ID_FACTURA)
        REFERENCES FACTURAS (ID_FACTURA),
CONSTRAINT FK_MERCANCIA FOREIGN KEY (ID_MERCANCIA)
        REFERENCES MERCANCIA (ID_MERCANCIA)
);

CREATE TABLE MERCANCIA(
ID_MERCANCIA VARCHAR(255),
TIPO VARCHAR(255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCACIA),
CONSTRAINT NN_TIPO CHECK (TIPO IS NOT NULL)
);

CREATE TABLE MERCANCIA_EN_CAMION(
ID_MERCANCIA VARCHAR(255),
ID_CAMION VARCHAR(255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT PK_CAMION PRIMARY KEY (ID_CAMION),
CONSTRAINT FK_CAMION FOREIGN KEY (ID_CAMION)
          REFERENCES CAMION (ID_CAMION)
);

CREATE TABLE MERCANCIA_EN_BUQUE(
ID_MERCANCIA VARCHAR(255),
ID_BUQUE VARCHAR (255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT FK_MERCANCIA FOREIGN KEY (ID_MERCANCIA)
        REFERENCES MERCANCIA (ID_MERCANCIA),
CONSTRAINT PK_BUQUE PRIMARY KEY (ID_BUQUE),
CONSTRAINT FK_BUQUE FOREIGN KEY (ID_BUQUE)
              REFERENCES BUQUES (ID_BUQUE)
);

CREATE TABLE MERCANCIA_EN_ALMACENAMIENTO(
ID_MERCANCIA VARCHAR(255),
ID_ALMACENAMIENTO VARCHAR(255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT FK_MERCANCIA FOREIGN KEY (ID_MERCANCIA)
              REFERENCES MERCANCIA (ID_MERCANCIA),
CONSTRAINT PK_ALMACENAIENTO PRIMARY KEY (ID_ALMACENAMIENTO),
CONSTRAINT FK_ALMACENAMIENTO FOREIGN KEY (ID_ALMACENAMIENTO)
        REFERENCES AREA_ALMACENAMIENTO (ID_ALMACENAMIENTO)
);

CREATE TABLE CARGA_DESCARGA_MARITIMA(
ID_MERCANCIA VARCHAR(255),
ID_BUQUE VARCHAR(255),
ID_ALMACENAMIENTO VARCHAR(255),
TIPO VARCHAR(255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT FK_MERCANCIA FOREIGN KEY (ID_MERCANCIA)
        REFERENCES MERCANCIA (ID_MERCANCIA),
CONSTRAINT PK_BUQUE PRIMARY KEY (ID_BUQUE),
CONSTRAINT FK_BUQUE FOREIGN KEY (ID_BUQUE)
          REFERENCES BUQUES (ID_BUQUE),
CONSTRAINT PK_ALMACENAMIENTO PRIMARY KEY (ID_ALMACENAMIENTO),
CONSTRAINT FK_ALMACENAMIENTO FOREIGN KEY (ID_ALMACENAMIENTO)
          REFERENCES AREA_ALMACENAMIENTO (ID_ALMACENAMIENTO),
CONSTRAINT PK_TIPO PRIMARY KEY (TIPO)
);

CREATE TABLE CARGA_DESCARGA_TERRESTRE(
ID_MERCANCIA VARCHAR(255),
ID_CAMION VARCHAR(255),
ID_ALMACENAMIENTO VARCHAR(255),
TIPO VARCHAR(255),
CONSTRAINT PK_MERCANCIA PRIMARY KEY (ID_MERCANCIA),
CONSTRAINT FK_MERCANCIA FOREIGN KEY (ID_MERCANCIA)
        REFERENCES MERCANCIA (ID_MERCANCIA),
CONSTRAINT PK_CAMION PRIMARY KEY (ID_CAMION),
CONSTRAINT FK_CAMION FOREIGN KEY (ID_CAMION)
          REFERENCES CAMION (ID_CAMION),
CONSTRAINT PK_ALMACENAMIENTO PRIMARY KEY (ID_ALMACENAMIENTO),
CONSTRAINT FK_ALMACENAMIENTO FOREIGN KEY (ID_ALMACENAMIENTO)
          REFERENCES AREA_ALMACENAMIENTO (ID_ALMACENAMIENTO),
CONSTRAINT PK_TIPO PRIMARY KEY (TIPO)
);