SELECT *
FROM MOVIMIENTO_BUQUES 
WHERE FECHA BETWEEN TO_DATE('06-02-2016','DD-MM-YYYY')
     AND TO_DATE('10-02-2016','DD-MM-YYYY')
  AND ID_BUQUE NOT IN (SELECT ID_BUQUE
                    FROM BUQUES 
                    WHERE NOMBRE = 'Barco66' 
                      AND TIPO_BUQUE = 'RORO');
                      
CREATE INDEX IND_COMPUESTO ON BUQUES(TIPO_BUQUE,NOMBRE);

DROP INDEX IND_COMPUESTO;